### Title

In [2]:
import numpy as np
import uklad
import potegowa

In [3]:
def gram_schmidt(matrix):
    matrix = matrix.astype(float)
    n = matrix.shape[0]
    V=matrix.copy() #
    Q=matrix.copy() # Wektor
    R=np.zeros([n,n])
    for j in range(0,n):
        for i in range(0,j):
            R[i,j]=Q[:,i].T @ matrix[:, j] # vector @ Column
            V[:,j]=V[:,j]-R[i,j]*Q[:,i] # R[i,j] @ VECTOR
        R[j,j]=np.linalg.norm(V[:,j]) # Sets diag to norm of V[Column] matrix
        Q[:,j]=V[:,j]/R[j,j] #Dzielenie Kolumny przez norme kolumny
    return Q,R

A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
gram_schmidt(A)

(array([[ 0.85714286, -0.39428571, -0.33142857],
        [ 0.42857143,  0.90285714,  0.03428571],
        [-0.28571429,  0.17142857, -0.94285714]]),
 array([[ 14.,  21., -14.],
        [  0., 175., -70.],
        [  0.,   0.,  35.]]))

Sprawdzenie czy A = Q * R jest spełnione

In [4]:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
q,r = gram_schmidt(A)
q,r,q@r,np.diag(q.T@A)

(array([[ 0.85714286, -0.39428571, -0.33142857],
        [ 0.42857143,  0.90285714,  0.03428571],
        [-0.28571429,  0.17142857, -0.94285714]]),
 array([[ 14.,  21., -14.],
        [  0., 175., -70.],
        [  0.,   0.,  35.]]),
 array([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]]),
 array([ 14., 175.,  35.]))

In [5]:
def eig_qr0(matrix, eps=2e-10):
    it = 0
    n = matrix.shape[0]
    matrix = np.tril(matrix, -1) + np.triu(matrix) #-1 so we don't get numbers on diag
    k = n
    while True:# Matrix[row][column]
        if abs(matrix[k - 1][k - 2]) <= 2 * eps * (abs(matrix[k - 2][k - 2]) + abs(matrix[k - 1][k - 1])):
            matrix[k - 1][k - 2] = 0
            k = k - 2
        elif abs(matrix[k - 1][k - 2]) <= 2 * eps * (abs(matrix[k - 1][k - 1]) + abs(matrix[k - 1][k - 1])):
            matrix[k - 1][k - 2] = 0
            k = k - 1
        else:
            if it >= 1000 * n:
                return [], []
            Q, R = gram_schmidt(matrix[:k, :k]) # QR decomposition on k x k Matrix
            matrix[:k, :k] = R @ Q # Rebuilding Hessenberg matrix
            it = it + 1
    eigens_values = np.diagonal(matrix)
    return eigens_values, it


a,b  = eig_qr0(r @ q) #
a,b

KeyboardInterrupt: 

Porowanienie Metod

In [15]:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
u1 =uklad.Uklad()
u1.losuj_uklad()
u1.zadaj_uklad(macierz = A,wektor = np.array([0,0,0]))

p1 = potegowa.Potegowa(u1)
iter_potegowa = p1.iteruj_roznica(eps=2e-10,wyswietlaj = 0)
q,r = gram_schmidt(u1.A)
eigens,iter_qr = eig_qr0(r @ q)
print(np.linalg.eigvals(A),iter_qr,iter_potegowa,np.max(eigens))

[156.13668406  16.05999094 -34.196675  ] 31 22 156.13668406196882


In [6]:
np.linalg.eigvals(A)

array([156.13668406,  16.05999094, -34.196675  ])